### PR TITLE
Biblatex options

### PR DESCRIPTION
**Pull request by jakobhaervig**
Added the `style=numeric-comp` option to biblatex package in the preamble and the `title=Bibliography` option to the printbibliography command

### CODE REVIEW

**Comment by eyJhb** [comment]
But isn't this just personal preference that could be changed after cloning the repo, etc.?

**Comment by jakobhaervig** [comment]
You're right. However, as this template acts as the official AAU LaTeX template for student, I feel we could make it a bit more accessible for the students without sacrificing template simplicity. I keep getting such questions from students (especially 1 year students) who have to use bibliography style different from the standard and don't have the required LaTeX knowledge yet.

**Comment by jkjaer** [comment]
I am fine with including the style=numeric-comp. As far as I can see, the main difference to the default style numeric is that [1,2,3] is written as [1-3].

What is the motivation for adding the option title=Bibliography? On my system, this is already the default title. It is to make it easier for the students to change it?

**Comment by jakobhaervig** [comment]
We could simply use `style=numeric` instead. That should be the exact one currently being used. Yes, the title option is simply to make it easier for students to change it. Students on their first semesters typically write in Danish so "Referencer" would be more approriate for them.

**Comment by jkjaer** [comment]
I think it is a good idea to include default options for things students often change. However, I do not think your use case example is particularly good since students should change the default language in the preamble instead of just changing the bibliography title. Changing the language will also automatically translate figures, tables, etc.

I will merge your change into the main branch, but I will also add a  comment about the language option.

**Pull request merged**
