### PR TITLE
Natbib implementation

### PR DESCRIPTION
**Pull request by jakobhaervig**
Across the different studies at AAU students prefer to use different bibliography styles. The natbib package makes it a bit easier to mange the bibliography. I changed the master.tex and preamble.tex accordingly

### CODE REVIEW

**Comment by eyJhb** [comment]
Wouldn't it make more sense, to use e.g. biblatex? 
https://tex.stackexchange.com/questions/25701/bibtex-vs-biber-and-biblatex-vs-natbib

**Comment by eyJhb** [comment]
https://github.com/jkjaer/aauLatexTemplates/blob/e0c1524bb769338fb5bdad83e26df78258068e70/aauReportTemplate/setup/preamble.tex#L116-L122
Also, shouldn't these but moved around? `\captionsdanish` seems to be the english one.

**Comment by jkjaer** [comment]
As far as I understand it, biblatex is more modern and flexible than natbib so I would also support that as the default. However, we can leave the natbib stuff in there as a comment so people can use it they prefer it over biblatex.

**Comment by jakobhaervig** [comment]
You are right. I was not aware of the full functionality of biblatex. I'll do a new pull request with small changes to the biblate setup

**Pull request closed without merging**
