### PR TITLE
fix image resolution

### PR DESCRIPTION
**Pull request by biocyberman**
This fixes a problem with image resolution when using theme as a result of running `install.sh`

### CODE REVIEW

**Comment by biocyberman** [comment]
This PR works make themes work on both Linux and MacOS without the need to store any theme files under user project/directory. 

So the workflow is like this:
- install theme: `git clone https://github.com/jkjaer/aauLatexTemplates.git; cd aauLatexTemplates; ./install.sh`
- Use theme: `cd <my/latex/documents>` and use themes like any  other standard beamer themes.

**Comment by eyJhb** [comment]
Something is very off with this PR, I cannot seem to figure out, where the notice went? No commits show you removed it, but either way, it is not there anymore. Is it just me?

**Comment by biocyberman** [comment]
@eyJhb  Not sure what you mean. I still see the comit and PR. See screenshot of what I am seeing below.

Screenshot 2019-04-28 at 18 52 00

**Comment by jkjaer** [comment]
Hi. Sorry for the late reply. I also see the PR. Do you still don't see it, @eyJhb ?

**Comment by eyJhb** [comment]
It is more, that the notice in the remote repo, is completely gone and the commits/files changed does not indicate this
https://github.com/biocyberman/aauLatexTemplates/blob/dev/install.sh
https://github.com/jkjaer/aauLatexTemplates/blob/master/install.sh

This is what is screwing me over....

**Comment by eyJhb** [comment]
Nevermind, just blind. But I think that we should still have a notice @biocyberman  :)
So that people at least knows, what the install does!

And have you confirmed that the graphics works too, without being in the same folder?

**Comment by biocyberman** [comment]
> Nevermind, just blind. But I think that we should still have a notice @biocyberman :)
> So that people at least knows, what the install does!
> 
> And have you confirmed that the graphics works too, without being in the same folder?

@eyJhb Yes, the graphics works for me so I don't need to save a copy of theme files for every repo I make.

**Pull request merged**
